export enum TipoLocal {
  ROTATORIA = 'ROTATÓRIA',
  PRACA = 'PRAÇA',
  CRUZAMENTO_SEM_SEMAFORO = 'CRUZAMENTO SEM SEMÁFORO',
  CRUZAMENTO_COM_SEMAFORO = 'CRUZAMENTO COM SEMÁFORO',
  PONTO_ONIBUS = 'PONTO DE ÔNIBUS',
  TERMINAL_INTEGRACAO = 'TERMINAL DE INTEGRAÇÃO',
  PLATAFORMA_ESTACAO = 'PLATAFORMA / ESTAÇÃO',
  GARAGEM = 'GARAGEM',
  PISTA_RETA = 'PISTA RETA',
}
