export * from './usuario.model';
export * from './veiculo.model';
export * from './motorista.model';
export * from './trecho.model';
export * from './sexo.enum';
export * from './terceirizado.enum';
export * from './status.enum';
export * from './status-motorista.enum';
export * from './combustivel.enum';
