version: '3.8'

services:
  # PostgreSQL Database
  postgres:
    image: postgres:15
    container_name: omni_postgres
    environment:
      POSTGRES_DB: omni_db
      POSTGRES_USER: omni_user
      POSTGRES_PASSWORD: omni_password
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    restart: unless-stopped

  # Backend API
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: omni_backend
    environment:
      NODE_ENV: production
      PORT: 3000
      DB_HOST: postgres
      DB_PORT: 5432
      DB_USERNAME: omni_user
      DB_PASSWORD: omni_password
      DB_DATABASE: omni_db
      JWT_SECRET: your-super-secret-jwt-key-for-production
      JWT_EXPIRATION: 1d
    ports:
      - "3000:3000"
    depends_on:
      - postgres
    restart: unless-stopped

  # Nginx para servir o frontend
  nginx:
    image: nginx:alpine
    container_name: omni_nginx
    ports:
      - "80:80"
    volumes:
      - ./frontend/dist/frontend:/usr/share/nginx/html
      - ./nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - backend
    restart: unless-stopped

volumes:
  postgres_data: